version: '3.2'
services:
    react-test:
        build: .
        ports:
            - "8000:3000"
        # env_file:
        #     - .env_dev
        volumes:
            - ${PWD}/src:/app/src
            # - /app/node_modules
        command: ["npm", "start"]
